# fly.toml app configuration file generated for ghar-ka-zaiqa-vlnrla on 2026-07-04T20:56:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ghar-ka-zaiqa-vlnrla'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = "uvicorn backend.server:app --host 0.0.0.0 --port 8080"

[env]
  DB_NAME = 'gharkazaiqa'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
